backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  #name: github
  #repo: dreon/rengo-11ty-decap
media_folder: "/assets/img"
public_folder: "/assets/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: false
# publish_mode: editorial_workflow
collections:
  - label: "Metadata"
    name: "Metadata"
    extension: json
    format: json
    editor:
      preview: true
    files:
      - label: "Metadata Items"
        name: "Metadata Items"
        file: "_data/metadata.json"
        fields:
          - label: Metadata Fields
            name: Metadata Fields
            widget: list
            allow_add: true
            collapsed: true
            fields:
              - { name: 'name' }
              - { name: 'author' }
              - { name: 'url' }

  - label: "Jason Rengstorf On/Off"
    name: "jason-is"
    extension: json
    format: json
    editor:
      preview: false
    files:
      - label: "Jason's On/Off"
        name: "jason-onoff"
        file: "_data/jason.json"
        fields:
          - label: Jason's On/Off
            name: jason-onoff
            widget: list
            allow_add: true
            collapsed: true
            summary: 'Jason is ... {{fields.body}}'
            fields:
              - { name: 'onoff', widget: "boolean"} 
              - { name: 'body'}