backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  #name: github
  repo: dreon/rengo-11ty-decap
media_folder: "assets/img"
public_folder: "/assets/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Metadata"
    name: "Metadata"
    file: "_data/metadata.json"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Author, name: author, widget: string }
      - { label: URL, name: url, widget: string }